### ISSUE TITLE
Bot doesn't automatically posts new release updates

### ISSUE THREAD

**Issue by 1000101** [pyatyispyatil/github-releases-notify-bot#6]
Hi, is the bot still working? I have been using it for the past few months without any problems but I haven't received any notification since 22.02.2019.

**Comment by pyatyispyatil** [comment]
It still works. Perhaps something happened to github graphql api. I have already added logging for this and now I am watching for errors.

**Comment by 1000101** [comment]
Thanks, it started to work again! (2 mins ago)
