### ISSUE TITLE
Bot is unresponsive (mostly)

### ISSUE THREAD

**Issue by spookyahell** [pyatyispyatil/github-releases-notify-bot#8]
[@github_releases_notify_bot](https://t.me/github_releases_notify_bot) on Telegram is somehow not currently responding correctly to commands
And also not sending notifications upon new releases...

This is a message to inform the operator about the circumstance
and in hopes it will be fixed...

**Comment by spookyahell** [comment]
Okay, great, issues are resolved apparently
I wonder - did the maintainer need to do sth to make it happen?
Anyway... closing this issue now

**Comment by pyatyispyatil** [comment]
I had to restart mongodb on the server.  After a long time of uptime, the node lost connection with the database and could not read or write.  I did not have time to investigate this problem. =(

**Comment by josef-v** [comment]
Bot is unresponsive again. We were thinking about running our own instance, which is quite easy, I have tried. But I somehow worry about us encountering this issue. Is restart of mongodb enough to resolve it (I expect that this is the same issue as last time)?
Btw, thanks for the bot, it helps a lot.

**Comment by spookyahell** [comment]
> 
> 
> Bot is unresponsive again. We were thinking about running our own instance, which is quite easy, I have tried. But I somehow worry about us encountering this issue. Is restart of mongodb enough to resolve it (I expect that this is the same issue as last time)?
> Btw, thanks for the bot, it helps a lot.

IF you do run your own instance please consider to share the username you are running it under... might help others too....

**Comment by josef-v** [comment]
> (I expect that this is the same issue as last time)
Oh... I thought I am reacting to the issue from 25th September #7 . This seems as a different problem. 
@spookyahell Sorry, but it would be a private instance just for our team. But I would consider writing an easy to follow step-by-step guide on how to run your own instance if it helped.
